spring:
  datasource:
    #    url: jdbc:h2:file:./db/new_file;AUTO_SERVER=true;MODE=POSTGRES;NON_KEYWORDS=KEY,LEVEL,VALUE
    #    username: new_file
    #    password:
    #    driver-class-name: org.h2.Driver
    url: jdbc:postgresql://localhost:5432/crm_bff
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        #        dialect: org.hibernate.dialect.H2Dialect
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 100
  h2:
    console:
      enabled: true
#      path: /h2-ui

jwt:
  app:
    jwtSecret: ======================Jwt=Spring===========================
    jwtExpirationMs: 86400000

app:
  response-wrapping:
    enabled: true
    enable-result-logging: false
    wrapper-class-name: kg.founders.common.models.wrapper.WrapperResponseMessage



