spring:
  profiles: test
  datasource:
    url: ${CREDIT_DB_URL:jdbc:postgresql://localhost:5432/logistic}
    username: ${CREDIT_DB_USERNAME:postgres}
    password: ${CREDIT_DB_PASSWORD:1209}
    driver-class-name: org.postgresql.Driver